import { Priority, Task } from './types'

export const initialTaskList: Task[] = [
  { description: "Tidy my room", priority: Priority.Low, storyPoints: 5 },
  { description: "Go shopping", priority: Priority.High, storyPoints: 3 },
  { description: "Cook breakfast", priority: Priority.High, storyPoints: 13 },
  { description: "Meet friends", priority: Priority.Medium, storyPoints: 3 },
  { description: "Walk the dog", priority: Priority.Medium, storyPoints: 2 },
  { description: "Call parents", priority: Priority.Low, storyPoints: 1 },
  { description: "Water plants", priority: Priority.Medium, storyPoints: 8 },
  { description: "Write a blog post", priority: Priority.Medium, storyPoints: 5 },
  { description: "Plan vacation", priority: Priority.High, storyPoints: 8 },
  // { description: "Organize closet", priority: Priority.Low, storyPoints: 5 },
  // { description: "Study for exam", priority: Priority.High, storyPoints: 13 },
  // { description: "Clean car", priority: Priority.Medium, storyPoints: 3 },
  // { description: "Grocery shopping", priority: Priority.Medium, storyPoints: 1 },
  // { description: "Update resume", priority: Priority.High, storyPoints: 8 },
  // { description: "Meditate", priority: Priority.Low, storyPoints: 2 },
  // { description: "Prepare presentation", priority: Priority.High, storyPoints: 8 },
  // { description: "Watch a movie", priority: Priority.Low, storyPoints: 3 },
  // { description: "Attend workshop", priority: Priority.Medium, storyPoints: 5 },
  // { description: "Fix the sink", priority: Priority.High, storyPoints: 13 },
  // { description: "Send emails", priority: Priority.Medium, storyPoints: 3 },
  // { description: "Work on hobby project", priority: Priority.Low, storyPoints: 5 },
  // { description: "Visit the doctor", priority: Priority.High, storyPoints: 2 },
  // { description: "Plan weekly meals", priority: Priority.Medium, storyPoints: 5 },
  // { description: "Review finances", priority: Priority.High, storyPoints: 5 },
  // { description: "Take a walk", priority: Priority.Low, storyPoints: 2 },
  // { description: "Attend meeting", priority: Priority.High, storyPoints: 5 },
  // { description: "Write code", priority: Priority.Medium, storyPoints: 8 },
  // { description: "Organize files", priority: Priority.Low, storyPoints: 1 },
  // { description: "Cook dinner", priority: Priority.High, storyPoints: 5 }
].map((x, i) => ({...x, id: i}));
